### ISSUE TITLE
Create homepage for application

### ISSUE THREAD

**Issue by j-moudy** [yesollee1/CS160BudgetApp#1]
Create a homepage for the application, which will list the current expenses (if any). There will be buttons to add an expense or create a goal. 
- [x] Add buttons to the layout.xml file for above features.

- [x] Add intents to buttons for transferring to different activity for the above features.

**Comment by jaimeadele** [comment]
I think this should be the same as the expense page, which is already a separate task/issue.

**Comment by canhuynh1998** [comment]
I have created a page that has 3 buttons Goal List, Expense List, and Transaction List. They will link to the respective list

**Comment by canhuynh1998** [comment]
I will close this issue for now.
