### ISSUE TITLE
Implement FireBase 

### ISSUE THREAD

**Issue by j-moudy** [yesollee1/CS160BudgetApp#2]
Implement Google firebase features for user authentication and database connectivity for the application. 

- [x] Implement user authentication to allow users to sign in their Google accounts. 

- [x] Implement database connectivity for the application through Firebase.

**Comment by canhuynh1998** [comment]
@Woneibra13, @mrcyrilgoud  can you guys merge and resolve the conflict if we still have any?

**Comment by Woneibra13** [comment]
We will try a merge soon!

**Comment by Woneibra13** [comment]
User sign-in with firebase implemented.
